export const alphabetConstants = {
  REQUESTED_ALPHABET: "REQUESTED_ALPHABET",
  REQUESTED_ALPHABET_SUCCEEDED: "REQUESTED_ALPHABET_SUCCEEDED",
  REQUESTED_ALPHABET_FAILED: "REQUESTED_ALPHABET_FAILED"
};
